version: "3.8"
services:
  db:
    image: postgres:15.7
    container_name: pekilla_db
    ports:
      - "5000:5432"
    env_file:
      - "./env.properties"

  mail_server:
    image: axllent/mailpit
    container_name: pekilla_mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1