server:
  port: ${PORT}
spring:
  docker:
    compose:
      lifecycle-management: start_only
  mail:
    host: localhost
    port: 1025
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
  datasource:
    url: ${URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: always
  config:
    import: file:env.properties

logging:
  level:
    org:
      springframework:
        security: DEBUG